name: AcademicHUB CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /data/www/academichub.us.to
          git pull origin main
          mv /data/www/academichub.us.to/backend/* /data/www/api.academichub.us.to
          mv /data/www/academichub.us.to/frontend/* /data/www/academichub.us.to
          cd /data/www/api.academichub.us.to
          composer install --no-dev
          cd /data/www/academichub.us.to
          npm install
          
          
